export enum FastAuthSignerErrorCodes {
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS",
    UNSUPPORTED_ALGORITHM = "UNSUPPORTED_ALGORITHM",
    UNSUPPORTED_MESSAGE_SIGNATURE = "UNSUPPORTED_MESSAGE_SIGNATURE",
}
